### ISSUE TITLE
Trying to delete clients doesn't work

### ISSUE THREAD

**Issue by theshades** [google/grr-doc#110]
Saying data_store not defined... ?

In [3]: print data_store.REL_DB.ReadClientSnapshot(u"C.83558528f50f993e")
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/console.pyc in <module>()
----> 1 print data_store.REL_DB.ReadClientSnapshot(u"<redacted>")

NameError: name 'data_store' is not defined

**Comment by mbushkov** [comment]
Does running `from grr_response_server import data_store` before the other commands help?

**Comment by alexgumo7** [comment]
Hi, after importing data_store:
`from grr_response_server import data_store`
and trying to delete a client with:
`data_store.REL_DB.DeleteClient(u"C.83558528f50f993e"`
I have the following error:
`
IntegrityError: (1451, 'Cannot delete or update a parent row: a
foreign key constraint fails (grr.client_paths, CONSTRAINT
client_paths_ibfk_2 FOREIGN KEY (client_id, path_type,
path_id, last_stat_entry_timestamp) REFERENCES
client_path_stat_entries (client_id, path_)')
`

**Comment by mbushkov** [comment]
@alexgumo7 , quick question - which GRR server version is this?

**Comment by mrhania** [comment]
@alexgumo7 This seems exactly as the same issue mentioned in google/grr#745. It should be fixed since google/grr@3440b00.

Because these issues are not related to the GRR documentation itself, I will close it. Feel free to reopen the issue in the main repo or open a new one if the problem persists.
