### ISSUE TITLE
errors encountered while processing grr-server.

### ISSUE THREAD

**Issue by kevinHarianto** [google/grr-doc#150]
[mysql(the Configuration).txt](https://github.com/google/grr-doc/files/10155785/mysql.the.Configuration.txt)
after setting up mysql with [mysqld] from directly following the queries
max_allowed_packet=90M from directly following the queries. i still get an error in relation to the limited amount of 
the allowed packets.
[error.txt](https://github.com/google/grr-doc/files/10155722/error.txt)

i cant seem to connect to the grr server in response to this issue despite the status saying that it is up

**Comment by panhania** [comment]
I see that you closed #151 and that seems to be the same issue, so I will close this one as well. If you have other issues, please post them to the main GRR repository (https://github.com/google/grr/issues).
