### ISSUE TITLE
Error Restoring Database

### ISSUE THREAD

**Issue by Hookapelli** [google/grr-doc#22]
Hi All,

Trying to do a DB reset after testing before I go into production. Following is an exert from the server... 

xxxxxxt@GRR:/usr/share/grr/scripts$ bash database_reset.sh
[sudo] password for xxxxxxxt:
grr-http-server start/running, process 950
Stopping grr-http-server
grr-http-server stop/waiting
Dropping database
database_reset.sh: line 12: mongo: command not found
grr-http-server stop/waiting
Starting grr-http-server
grr-http-server start/running, process 1602

##################################################
Here's a copy of database_reset.sh

stop_services $GRR_SERVICES
echo "Dropping database"
echo "db.dropDatabase()" |  mongo grr
stop_services $GRR_SERVICES

Any ideas?

**Comment by brian-olson** [comment]
Hi HookaPelli,

That script resets the (formerly) default Mongo database. If you've
recently installed v3.0.0.7 I think mongo has been completely removed and
that script should be removed from the repo. Can you confirm what datastore
you're using (Datastore.implementation) in /etc/grr/grr-server.yaml OR
/etc/grr/server.local.yaml.

Something I've done in the past was to just change the name of the db
(Mysql.database_name) to create a completely fresh db while retaining the
old one for further testing in the future.

Brian

**Comment by destijl** [comment]
That script is now gone, as is mongo.
