### ISSUE TITLE
Unable to connect to Upstart, even though I replaced systemd with upstart

### ISSUE THREAD

**Issue by 1600** [google/grr-doc#36]
Environment :  Ubuntu 15.04 Desktop

Before installation by
wget https://raw.githubusercontent.com/google/grr/master/scripts/install_script_ubuntu.sh
sudo bash install_script_ubuntu.sh
I replaced systemd with upstart, as seen in the error below the sh script requires upstart, **## still this error was emitted**

Error Output----------------------------------------------------------------------------------------------------------------
...
...
/usr/share/grr/executables/darwin/templates/grr-client_3.0.0.7_amd64.pkg.xar repacked ok.

Initialization complete, writing configuration.
Please restart the service for it to take effect.

##########################################################################################
     Enable grr services to start automatically on boot
##########################################################################################

Run . /usr/share/grr/scripts/shell_helpers.sh [Y/n/a]? 
#### Running #### . /usr/share/grr/scripts/shell_helpers.sh

Run enable_services grr-http-server [Y/n/a]? 
#### Running #### enable_services grr-http-server
Starting grr-http-server
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Failed to start grr-http-server.service: Unit grr-http-server.service failed to load: No such file or directory.
#########################################################################################
FAILURE RUNNING: enable_services grr-http-server
#########################################################################################
sport@ubuntu:~$

**Comment by destijl** [comment]
As stated here the server is well-tested on 14.04:
https://github.com/google/grr-doc/blob/master/quickstart.adoc#requirements

I'm not sure why putting upstart back wasn't enough, you can try and debug yourself, or just use 14.04 which has the best current support window anyway. Once 16.04 is out we'll need to do some work to bring everything into systemd, but that isn't until April at the earliest.

If you got to that point in the script you essentially have a working install, all those last commands are doing is turning on the right services using this function:
https://github.com/google/grr/blob/master/scripts/shell_helpers.sh#L52

should be pretty easy to do that manually.
