### ISSUE TITLE
Not an issue just assistance

### ISSUE THREAD

**Issue by sweendogg007** [google/grr-doc#45]
Hi,

I am testing out grr using Docker "goofy_kare" build and am having issues with my Mac OS el capitan GRR agent talking to the docker image.

Need Clarity around the following:
To get the GRR agent and debug agent to run in El Captian, do i just need to download the agent from the manage binaries tab in the GRR Docker portal and install the .pkg files published here? 
Or do i need to do anything with vagrant to get the agent to talk to the server?

Platform:
Mac OS X El capitan using Kitematic and Goofy_Kare GRR build.

Thanks
Chris

**Comment by destijl** [comment]
Hey, yes just download the binary from the UI and install. Is this built off head? You can follow the client troubleshooting instructions here:
https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#i-dont-see-my-clients

Also note OS X had some docker networking problems last I tried, noted here:
https://github.com/google/grr-doc/blob/master/docker.adoc

**Comment by sweendogg007** [comment]
Hi,

Thanks for the quick response.

I have created a new docker image using the command highlighted in the article.

What is the best way to remove the old agent on the Mac OS X, I am unable to use the "On OSX you can also use the Uninstall flow.” method

Thanks
C


Loading configuration from /usr/local/lib/grr/grr_3.0.7.1_amd64/grr.yaml

Starting installation procedure for GRR client.

Initializing Installer

Initializing OSXInstaller

Extracting config file from .pkg.

Missing config definition for Client.server_urls. This option is likely deprecated or renamed. $

Missing config definition for Client.build_environment. This option is likely deprecated or ren$

Loading configuration from /etc/grr.local.yaml

Configuration writeback is set to /etc/grr.local.yaml

Writing back configuration to file /etc/grr.local.yaml

Config file extracted successfully.

Extracting additional files.

**Comment by destijl** [comment]
Just delete all the files from /usr/local/lib/grr and the /Library/LaunchDaemons/ entry.

The install above looks mostly successful. What happens when you run it with --verbose as in the troubleshooting?

**Comment by sweendogg007** [comment]
Hi Greg,

Thanks for the reply

I get the following.


Chriss-MacBook-Pro:grr_3.0.7.1_amd64 chrissweeney$ sudo ./grr --verbose

Traceback (most recent call last):

  File "<string>", line 81, in <module>

  File "/Users/vagrant/mac-build/workpath/grr/out00-PYZ.pyz/grr.lib.flags", line 107, in StartMain

  File "<string>", line 57, in main

  File "/Users/vagrant/mac-build/workpath/grr/out00-PYZ.pyz/grr.lib.startup", line 71, in ClientInit

  File "/Users/vagrant/mac-build/workpath/grr/out00-PYZ.pyz/grr.lib.startup", line 38, in ConfigInit

  File "/Users/vagrant/mac-build/workpath/grr/out00-PYZ.pyz/grr.lib.config_lib", line 1436, in ParseConfigCommandLine

  File "/Users/vagrant/mac-build/workpath/grr/out00-PYZ.pyz/grr.lib.config_lib", line 1011, in __getitem__

  File "/Users/vagrant/mac-build/workpath/grr/out00-PYZ.pyz/grr.lib.config_lib", line 1049, in Get

RuntimeError: Error while retrieving Config.writeback: Configuration hasn't been initialized yet.

**Comment by destijl** [comment]
I just tested the latest docker build:
https://hub.docker.com/r/grrdocker/grr/builds/bqflshwiquc2upwdm6aqdce/

on OS X el cap and all works as expected. The above looks like an install issue. I installed with:
```
sudo installer -pkg /path/to/grr.pkg -target /
```
