### ISSUE TITLE
Installer can't complete due to distorm3 requirement

### ISSUE THREAD

**Issue by lorz** [google/grr-doc#46]
Running the installation script throws an exception while collecting distorm3=3.3.1 (no matching distribution  found for distorm3=3.3.1 from -r  requirements.txt file line 29)

Tested in Ubuntu 14.10 LTS as root user.

**Comment by steelyG** [comment]
Agree with lorz. Tested in Ubuntu 14.04.

**Comment by destijl** [comment]
Filed a bug in the main project, thanks for the report.
