### ISSUE TITLE
Clients dont show up in Admin UI

### ISSUE THREAD

**Issue by lodr74** [google/grr-doc#49]
I cant find my clients in the admin UI. 

I followed the Troubleshooting guide and no luck.  I do see the client installed on multiple systems.  Same results.  This is a snippet from one.  On all systems I am able to download the server.pem

[root@ip-172-31-8-37 ~]# ls /usr/lib64/grr/grr_3.1.0.2_i386/grrd
/usr/lib64/grr/grr_3.1.0.2_i386/grrd

[root@ip-172-31-8-37 ~]# ps -aux | grep grr
root     16886  0.0  0.0   2424   512 pts/0    S    22:08   0:00 /usr/lib64/grr/grr_3.1.0.2_i386/grrd --config=/usr/lib64/grr/grr_3.1.0.2_i386/grrd.yaml
root     16888  0.2  3.0  72888 30612 pts/0    Sl   22:08   0:01 /usr/lib64/grr/grr_3.1.0.2_i386/grrd --config=/usr/lib64/grr/grr_3.1.0.2_i386/grrd.yaml

[root@ip-172-31-8-37 ~]# cat /var/log/grr_installer.txt
Loading configuration from /usr/lib64/grr/grr_3.1.0.2_i386/grrd.yaml
Loading configuration from /usr/lib64/grr/grr_3.1.0.2_i386/build.yaml
Starting installation procedure for GRR client.
Initializing Installer
Redirecting to /bin/systemctl stop  grrd.service

[root@ip-172-31-8-37 ~]# /usr/lib64/grr/grr_3.1.0.2_i386/grrd --config /usr/lib64/grr/grr_3.1.0.2_i386/grrd.yaml --verbose
INFO:2016-07-18 22:20:33,670 log:197] Starting GRR Prelogging buffer.
INFO:2016-07-18 22:20:33,746 config_lib:1103] Loading configuration from /usr/lib64/grr/grr_3.1.0.2_i386/grrd.yaml
INFO:2016-07-18 22:20:33,751 config_lib:1103] Loading configuration from /usr/lib64/grr/grr_3.1.0.2_i386/build.yaml
INFO:2016-07-18 22:20:33,756 config_lib:1103] Loading configuration from /etc/grr.local.yaml
INFO:2016-07-18 22:20:33,756 config_lib:809] Configuration writeback is set to /etc/grr.local.yaml
DEBUG:2016-07-18 22:20:33,756 log:155] Initializing Logging subsystem.
DEBUG:2016-07-18 22:20:33,756 log:107] Will use logging engines ['stderr']
DEBUG:2016-07-18 22:20:33,757 registry:166] Initializing CommunicatorInit
DEBUG:2016-07-18 22:20:33,757 registry:166] Initializing CommsInit
DEBUG:2016-07-18 22:20:33,758 registry:166] Initializing VFSInit
DEBUG:2016-07-18 22:20:33,758 registry:166] Initializing InitHook
INFO:2016-07-18 22:20:33,792 comms:1490] Starting client aff4:/C.e0a1962c8bf444ba
DEBUG:2016-07-18 22:20:33,795 admin:314] Sending startup information.
INFO:2016-07-18 22:20:33,801 comms:1174] Server PEM re-keyed.
INFO:2016-07-18 22:20:33,827 comms:1338] aff4:/C.e0a1962c8bf444ba: Sending 2(779), Received 0 messages in 0.00859999656677 sec. Sleeping for 600.0

**Comment by lodr74** [comment]
Im also using IP versus hostnames in my yaml configs.

version info:

oot@ip-172-31-8-93:/opt# cat /usr/share/grr-server/version.ini 
[Version]
major = 3
minor = 1
revision = 0
release = 2
packageversion = %(major)s.%(minor)s.%(revision)spost%(release)s
packagedepends = %(major)s.%(minor)s.*

Client

[root@ip-172-31-2-150 ~]# cat /usr/lib64/grr/grr_3.1.0.2_i386/version.ini 
[Version]
major = 3
minor = 1
revision = 0
release = 2
packageversion = %(major)s.%(minor)s.%(revision)spost%(release)s
packagedepends = %(major)s.%(minor)s.*
[root@ip-172-31-2-150 ~]#

**Comment by destijl** [comment]
That looks successful, it sent 2 messages to the server. Did you search in the search box in the UI?

**Comment by lodr74** [comment]
yes I did the following:

ip:52. - nothing
<IP_ADDRESS> - nothing


I got to Show Stats and click on a few of those for the last 1-day and no results as well.  Thoughts?

**Comment by lodr74** [comment]
Never mind it is working.  I was looking for the AWS NAT IP.  I just thought to look for the RFC-1918 and that is what is being registered.

**Comment by scudette** [comment]
Of course GRR only shows what the client tells it and in a NAT situation,
the client has no idea what the external IP address is so it reports its
local private IP address and that is what is being stored in the database.
