### ISSUE TITLE
Default install but http request throws an error

### ISSUE THREAD

**Issue by icepaule** [google/grr-doc#59]
Hello group,
could someone help me with my grr installation on Ubuntu 16.04 server.

I followed the simple install script on a brand new server installtion and everything passed without an issue. Just when I access the grr-service on port 8000 I get the below error. - Any help would be highly appreciated.  :-)

Thanks a lot

Marcus

ValueError at /
need more than 1 value to unpack
Request Method: GET
Request URL:    http://192.168.178.51:8000/
Django Version: 1.8.3
Exception Type: ValueError
Exception Value:  
need more than 1 value to unpack
Exception Location: /usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/webauth.py in SecurityCheck, line 64
Python Executable:  /usr/share/grr-server/bin/python
Python Version: 2.7.12
Python Path:  
['/usr/share/grr-server/bin',
 '/usr/share/grr-server/lib/python2.7',
 '/usr/share/grr-server/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/share/grr-server/lib/python2.7/lib-tk',
 '/usr/share/grr-server/lib/python2.7/lib-old',
 '/usr/share/grr-server/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/share/grr-server/local/lib/python2.7/site-packages',
 '/usr/share/grr-server/local/lib/python2.7/site-packages/IPython/extensions']
Server time:    Sat, 3 Sep 2016 12:57:05 -0500

Environment:

Request Method: GET
Request URL: http://192.168.178.51:8000/

Django Version: 1.8.3
Python Version: 2.7.12
Installed Applications:
()
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware')

Traceback:
File "/usr/share/grr-server/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/webauth.py" in Wrapper
2.     return WEBAUTH_MANAGER.SecurityCheck(func, request, _args, *_kwargs)
   File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/webauth.py" in SecurityCheck
3.                                                   " ").split(" ", 1)

Exception Type: ValueError at /
Exception Value: need more than 1 value to unpack

**Comment by ashishmgupta** [comment]
@icepaule 

I am new to GRR too. 
Can you confirm If you could execute the below on your Ubuntu server without any error?

wget https://raw.githubusercontent.com/google/grr/master/scripts/install_script_ubuntu.sh
sudo bash install_script_ubuntu.sh

**Comment by grrrrrrrrr** [comment]
This looks like an error in Django. What version are you using? Did you set up the virtualenv as in the documentation?

**Comment by destijl** [comment]
Re-open if you still need help.
