### ISSUE TITLE
CentOS Install Documentation

### ISSUE THREAD

**Issue by peasead** [google/grr-doc#61]
I'm looking to install Grr server on a CentOS box, I think I've looked through all the documentation and the requisite Google searching, but I'm unable to find a way.

I've tried cutting apart the Dockerfile, the instal_linux.sh Vagrant file, and all the documentation I could find...I even said a Hail Mary and converted the .deb into a .rpm with Alien.

The closest I can find is `grr-doc/installfrompip.adoc`, but I'm not sure if that's the right way or not. I'd like a cleaner way than using a development workflow if possible.

Any help would be appreciated, thanks in advance.

**Comment by scudette** [comment]
Converting the deb to rpm should mostly work. The actual install process is
through pip. We use dh-virtualenv to build a virtual environment inside the
deb. This should be self contained (does not depend on the installer python
or any packages) so it should work on centos just as well.

I would say you will need to tweak the startup scripts a bit but not too
much.

**Comment by peasead** [comment]
Thanks @scudette 

I guess I didn't try the pip process outside of the virtualenv...I'll give that a shot and follow-up.

**Comment by scudette** [comment]
Ah that's not a supported configuration. Generally running python code
outside a virtual env is a bad idea. I actually meant you should install
your code as well as grr in the same virtual env.

**Comment by destijl** [comment]
You essentially need to find yum equivalents of the stuff installed with apt here, install with pip:
https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-from-pip

and then put the systemd scripts from here:
https://github.com/google/grr/tree/master/debian

in the right place to run the server components.
