### ISSUE TITLE
Server and Client communication issue

### ISSUE THREAD

**Issue by francesd919** [google/grr-doc#65]
Hi there,
#I have installed the GRR server as well as client properly, however, the client does not show up in the Admin UI. I tried the troubleshooting page at https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#i-dont-see-my-clients
and I am currently stuck at the last step where I run the server in verbose mode but did not get the expected output.
below is a screenshot of what I got
![ubuntu 64-bit desktop-2016-11-17-16-49-56](https://cloud.githubusercontent.com/assets/23516676/20377775/98841330-acf6-11e6-8231-f9eecb4f0f9b.png)

**Comment by scudette** [comment]
This looks good - try searching for the exact client id that is
reported in the admin ui. It is possible that the interrogate flow is
not run and we dont know anything about the client to search by
hostname or users.

**Comment by francesd919** [comment]
Hi, sorry for the late response.
First of all, I just want to clarify one thing: should I install the GRR client on the VM where my GRR server was installed?
I followed the instruction "Client and server can run on the same host for testing purposes."

I couldn't see my client on the Admin UI, and this means I have no idea what the client ID is.

Thank you and looking forward to your response.

Frances

**Comment by scudette** [comment]
You can search for "." to just list all clients. Your client id is the thing after the "C.". So in your case C.55577....

**Comment by francesd919** [comment]
Oh, thank you. I see my client now.
![image](https://cloud.githubusercontent.com/assets/23516676/20494578/71da6bbe-b082-11e6-8989-17c80b9fbfcd.png)

**Comment by francesd919** [comment]
Hi, scudette.
This may be a silly question- I can find the client using the search bar, but when I return to the 'homepage' of the admin UI, the client is still not showing there.

![image](https://cloud.githubusercontent.com/assets/23516676/20497869/b51940c8-b08f-11e6-8097-0d2cf347ad50.png)

**Comment by scudette** [comment]
I think the UI under recently accessed clients just shows the recent
clients which had an approval for. If you don't have the full access
control manager (the one that enforces approvals) this won't show anything.
