### ISSUE TITLE
Some console commands no longer work.

### ISSUE THREAD

**Issue by josarsepi** [google/grr-doc#67]
https://github.com/google/grr-doc/blob/master/user_manual.adoc#delete-a-client-and-all-of-its-data

No longer works.  There are probably others but I haven't been digging around on the console lately.

**Comment by grrrrrrrrr** [comment]
Hey,

What exactly is the error you get when running the delete command? I just tried it and it worked fine for me:

In [1]: cid="C.01c665d7acc16089"

In [2]: aff4.FACTORY.Delete(rdf_client.ClientURN(cid))

In [3]:

**Comment by josarsepi** [comment]
My mistake.  It appears my function call was incorrect.  I apologize for wasting time.

NameError: name 'rdf_Client' is not defined

FAIL.
