### ISSUE TITLE
New Ubuntu Distrub 16.04 Server Config and Tools don't work out

### ISSUE THREAD

**Issue by t0astGuy** [google/grr-doc#70]
Hello.

I just installed ubuntu 16.04 and ran the quick install script.  That generates a working server but the grr_server --config-help throws

grr_server --config_help
Traceback (most recent call last):
  File "/home/notroot/Desktop/GRR_ENV/lib/python2.7/site-packages/grr/tools/GRR_ENV/bin/grr_server", line 11, in <module>
    sys.exit(GrrServer())
  File "/home/notroot/Desktop/GRR_ENV/lib/python2.7/site-packages/grr/tools/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 82, in GrrServer
    flags.StartMain(grr_server.main)
  File "/home/notroot/Desktop/GRR_ENV/lib/python2.7/site-packages/grr/tools/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
    main([sys.argv[0]])
  File "/home/notroot/Desktop/GRR_ENV/lib/python2.7/site-packages/grr/tools/GRR_ENV/local/lib/python2.7/site-packages/grr/tools/grr_server.py", line 31, in main
    if flags.FLAGS.component.startswith("worker"):
AttributeError: 'NoneType' object has no attribute 'startswith'

I then followed the PIP install directions with virtualenv (listed in the trace above)

I continue to get issues with 
grr_fuse

grr_fuse
/home/notroot/Desktop/GRR_ENV/lib/python2.7/site-packages/grr/tools/GRR_ENV/local/lib/python2.7/site-packages/rdflib/plugins/parsers/structureddata.py:30: UserWarning: html5lib not found! RDFa and Microdata parsers will not be available.
  'parsers will not be available.')

/home/notroot/Desktop/GRR_ENV/lib/python2.7/site-packages/grr/tools/GRR_ENV/local/lib/python2.7/site-packages/rdflib/plugins/parsers/hturtle.py:32: UserWarning: html5lib not found! RDFa and Microdata parsers will not be available.
  'will not be available.')

CRITICAL:2017-02-02 12:35:42,944 fuse_mount:562] Could not start!
fusepy must be installed to run fuse_mount.py!
Try:
  sudo pip install fusepy

But fusepy is already installed.  I'm not sure what to do next to get this fully operational.

**Comment by destijl** [comment]
The config_help being broken is unexpected, I'm not sure what's wrong there. The second problem with rdflib should be fixed now, rdflib changed their dependencies with the new release:

https://github.com/google/rekall/commit/4144bc96960f4d86d557954e6c273dbbb5e26e7b#commitcomment-20806494

**Comment by destijl** [comment]
Oh I see, grr_server is just a wrapper for running the other components. The error message is right, you need to give it a component so it can tell you the config that applies to that component (each one can be different). So:

```
grr_server --component=worker --config_help
```
or just
```
grr_worker --config_help
```
