### ISSUE TITLE
Where can I find GRR build instructions?

### ISSUE THREAD

**Issue by jturner900** [google/grr-doc#81]
In particular, I'd like to know how to generate things like install_script_ubuntu.sh.  I'd like to tinker with the source code for personal customization.

**Comment by grrrrrrrrr** [comment]
Please have a look at https://github.com/google/grr-doc/blob/master/installfrompip.adoc#installing-grr-server-for-dev-ie-tracking-head

I'll close this issue, just reopen if you need anything else.
