### ISSUE TITLE
User Manual "Artifacts" section contains broken links

### ISSUE THREAD

**Issue by devyzr** [google/grr-doc#83]
In the paragraph

> GRR artifacts are defined in YAML, with a style guide [available here](https://github.com/ForensicArtifacts/artifacts/blob/master/docs/style_guide.adoc). We use a standard set of machine information collected from the host for variable interpolation. This collection of data is called the Knowledge Base (see [proto/knowledge_base.proto](https://github.com/google/grr/blob/master/proto/knowledge_base.proto)) and is referenced with a %%variable%% syntax.
> 
> The artifact defines where the data lives. Once it is retrieved by GRR a [parser ](https://github.com/google/grr/tree/master/parsers)can optionally be applied to turn the collected information into a more useful format, such as parsing a browser history file to produce URLs.

The style guide, knowledge base and parser links lead to 404s

**Comment by devyzr** [comment]
The "Defining New Artifacts" section also contains a broken link:

> New artifacts should be added to the [forensic artifacts repository](https://github.com/ForensicArtifacts/artifacts/tree/master/definitions). The changes can be imported into grr by running make in the grr/artifacts directory. This will delete the existing artifacts, checkout the latest version of the artifact repository, and add all of the yaml definitions into GRR’s directory. Running python setup.py build will have the same effect. The new artifacts will be available once the server is restarted.

**Comment by grrrrrrrrr** [comment]
Hey,

Thanks for reporting this, I fixed all the links. We actually plan on going over the documentation end of November, many parts are really outdated by now.

Just in case you didn't know, you can also directly modify the documentation with the edit button on top, it will generate a pull request for us...

Cheers,
-Andy

**Comment by devyzr** [comment]
> Just in case you didn't know, you can also directly modify the documentation with the edit button on top, it will generate a pull request for us...

I wasn't aware, thank you!
