### ISSUE TITLE
Invalid configuration option for Auditing

### ISSUE THREAD

**Issue by Feandil** [google/grr-doc#84]
https://github.com/google/grr/commit/204602dda80ac822060056d1e0993e18c17cfa47 removed the option ```Datastore.security_manager```, however the documentation still points to it in the auditing session, as the way to enable full access control: https://github.com/google/grr-doc/blame/master/admin.adoc#L373-L375
```
AdminUI Context:
  Datastore.security_manager: FullAccessControlManager
  API.DefaultRouter: ApiCallRouterWithApprovalChecksWithoutRobotAccess
```

I understand that simply using the last line is enough, but to avoid confusion (and errors when trying to configure the server), removing that line (``` Datastore.security_manager: FullAccessControlManager```) would be great!

**Comment by mbushkov** [comment]
HI! Thanks for reporting this. I've updated the docs: https://github.com/google/grr-doc/commit/490f67e36efb3b99bc98c8b9c94aa61a8a35d522

I'll close the issue for now. Please reopen or open a new one if you find more issues!
